services:
  postgres:
    image: postgres:16
    container_name: device_manager_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5442:5432"
    volumes:
      - ./Scripts:/docker-entrypoint-initdb.d
    networks:
      - deviceManager-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  deviceManager-net:
